import "./globals.css";
import ThemeProviders from "./ThemeProviders";
import Providers from "./Providers";
import Navbar from "./componets/Navbar";
import Footer from "./componets/Footer";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <ThemeProviders>
          <Navbar></Navbar>
            <div className="flex-grow">{children}</div>
            <Footer></Footer>
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  );
}
